// header file for curriculum section 1: ERSTE LERNEINHEIT
// (c) iSAQB e.V. (https://isaqb.org)
// ====================================================

// tag::DE[]
== {lesson} Analyse

Sicherheit in der Softwareentwicklung bedeutet oft einen höheren Aufwand bei Design, Entwicklung, Wartung und Betrieb einer Anwendung.
Diese Maßnahmen sollen die Sicherheit der Anwendung erhöhen und damit grundsätzliche Architekturziele unterstützen. Dazu gehört als Grundlage eine Analyse der folgenden Aspekte:
 - schützenswerte Daten und Systemfunktionen,
 - potentielle Angriffsvektoren
 - Umgang mit Problemen, die durch mögliche Sicherheitslücken entstehen.
Hinzu kommen gängige Richtlinien und Standards. Diese Analysen dienen als Grundlage für alle weiteren Sicherheitskonzepte.

// end::DE[]

// tag::EN[]
== {lesson} 1: Analysis
// end::EN[]



include::01-duration-terms.adoc[{include_configuration}]

include::02-learning-goals.adoc[{include_configuration}]

// references (if any!)
include::references.adoc[{include_configuration}]
