// tag::DE[]
|===
| Dauer: 105 Min. | Übungszeit: 30 Min.
|===

=== Begriffe und Konzepte

Sicherheit in der Softwareentwicklung bedeutet oft einen höheren Aufwand bei Design, Entwicklung, Wartung und Betrieb einer Anwendung.
Diese Maßnahmen sollen die Sicherheit der Anwendung erhöhen und damit grundsätzliche Architekturziele unterstützen. Dazu gehört als Grundlage eine Analyse der folgenden Aspekte:
- schützenswerte Daten und Systemfunktionen,
- potenzielle Angriffsvektoren
- Umgang mit Problemen, die durch mögliche Sicherheitslücken entstehen.
Hinzu kommen gängige Richtlinien und Standards. Diese Analysen dienen als Grundlage für alle weiteren Sicherheitskonzepte.

*Wichtige Begriffe:*

Risk Management, Risk Management Framework, Threat Modeling, Threat Management, Attack Tree, Angriffsvektor,
Betriebskonzept, Audit, Richtlinien, Standards, Business Context analysis, Risk appetite

// end::DE[]

// tag::EN[]
|===
| Duration: 105 min | Practice time: 30 min
|===

=== Terms and principles

Security in software development often involves greater effort when designing, developing, maintaining, and operating an application.
These measures are intended to increase the security of the application and thus support fundamental architectural objectives. This includes an analysis of the following aspects:
- data and system functions worth protecting
- potential attack vectors
- dealing with problems caused by potential security vulnerabilities.
In addition, there are common guidelines and standards. These analyses serve as the basis for all other security concepts.

*Important terms:*

Risk management, risk management framework, threat modeling, threat management, attack tree,
attack vector, operational concept, audit, guidelines, standards, business context analysis, risk appetite
// end::EN[]

