// tag::DE[]
|===
| Dauer: 135 Min. | Übungszeit: 0 Min.
|===

=== Begriffe und Konzepte
Webanwendungen laufen nicht als völlig isolierte Systeme, sondern sind von Infrastruktur umgeben. Um die Sicherheit zu erhöhen kommen immer wieder die gleichen Komponenten zum Einsatz. Dabei geht es nicht um spezifische Produkte eines Herstellers, sondern um die grundlegenden Ideen und Konzepte hinter diesen.

_Dieser Teil bezieht sich auf die Sicherheit von Web-Systemen. Für Informationssysteme oder Embedded Systeme müssen entsprechend andere Inhalte vermittelt werden._

*Wichtige Begriffe:*

WAF, DMZ, Firewall, IDS, IPS, Logging, Monitoring, Ongoing Feedback

// end::DE[]

// tag::EN[]
|===
| Duration: 135 min | Practice time: 0 min
|===

=== Terms and principles
Web applications do not run as completely isolated systems, but are surrounded by infrastructure. In order to increase security, the same components are used again and again. This is not about specific products from a manufacturer, but about the basic ideas and principles behind them.

_This section relates to the security of web systems. For information systems or embedded systems, other content must be conveyed accordingly._

*Important terms:*
WAF, DMZ, firewall, IDS, IPS, logging, monitoring, ongoing feedback

// end::EN[]

