// tag::DE[]
|===
| Dauer: 135 Min. | Übungszeit: 0 Min.
|===

=== Begriffe und Konzepte
Webanwendungen laufen nicht als völlig isolierte Systeme, sondern sind von Infrastruktur umgeben. Um die Sicherheit zu erhöhen kommen immer wieder die gleichen Komponenten zum Einsatz. Dabei geht es nicht um spezifische Produkte eines Herstellers, sondern um die grundlegenden Ideen und Konzepte hinter diesen.

_Dieser Teil bezieht sich auf die Sicherheit von Web-Systemen. Für Informationssysteme oder Embedded Systeme müssen entsprechend andere Inhalte vermittelt werden._

*Wichtige Begriffe:*

WAF, DMZ, Firewall, IDS, IPS, Logging, Monitoring, Ongoing Feedback

// end::DE[]

// tag::EN[]
|===
| Duration: XXX min | Practice time: XXX min
|===

=== Terms and Principles
* Term 1
* Term 2
* Term 3
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
