// tag::DE[]
|===
| Dauer: 240 Min. | Übungszeit: 30 Min.
|===

=== Begriffe und Konzepte
* Authentifizierungskonzepte
* Multi-Faktor
* Single Sign On
* Identity Management
* Federation
* Werkzeuge
* sichere Protokolle
* Autorisierungskonzepte
Konkrete Sicherheitsprobleme wie Authentifizierung oder sichere Datenübertragung werden oft mit technisch ähnlichen Maßnahmen gelöst.
Diese Lösungen setzen teilweise ein bestimmtes Anwendungsdesign voraus. Nachträgliches Refactoring in Richtung dieser Entwürfe ist oft mit hohen Aufwänden verbunden und an diesen kritischen Stellen fehleranfällig.

_Dieser Teil bezieht sich auf die Sicherheit von Web-Systemen. Für Informationssysteme oder Embedded Systeme müssen entsprechend andere Inhalte vermittelt werden._

// end::DE[]

// tag::EN[]
|===
| Duration: XXX min | Practice time: XXX min
|===

=== Terms and Principles
* Term 1
* Term 2
* Term 3
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
