// tag::DE[]
|===
| Dauer: 240 Min. | Übungszeit: 30 Min.
|===

=== Begriffe und Konzepte
Konkrete Sicherheitsprobleme wie Authentifizierung oder sichere Datenübertragung werden oft mit technisch ähnlichen Maßnahmen gelöst.
Diese Lösungen setzen teilweise ein bestimmtes Anwendungsdesign voraus. Nachträgliches Refactoring in Richtung dieser Entwürfe ist oft mit hohen Aufwänden verbunden und an diesen kritischen Stellen fehleranfällig.

_Dieser Teil bezieht sich auf die Sicherheit von Web-Systemen. Für Informationssysteme oder Embedded Systeme müssen entsprechend andere Inhalte vermittelt werden._

*Wichtige Begriffe:*

Authentifizierungskonzepte, Multi-Faktor, Single-Sign-On, Identity Management, Federation, Werkzeuge, sichere Protokolle, Autorisierungskonzepte

// end::DE[]

// tag::EN[]
|===
| Duration: 240 min | Practice time: 30 min
|===

=== Terms and principles
Specific security issues such as authentication or secure data transmission are often solved with technically similar measures. Some of these solutions require a specific application design. Subsequent refactoring in the direction of these designs is often associated with high expenses and is prone to errors at these critical points.

_This section relates to the security of web systems. For information systems or embedded systems, other content must be conveyed accordingly._

*Important terms:*

Authentication principles, multifactor, single sign-on, identity management, federation, tools, secure protocols, authorization concepts

// end::EN[]
