// tag::DE[]
=== Voraussetzungen

Die Voraussetzungen für das Training hängen von dem Bereich ab, auf den sich das Training fokussiert.

Beispielsweise sind die Voraussetzungen für Sicherheit im Web-Bereich:

- Grundkenntnisse Netzwerkkommunikation
- Grundkenntnisse in Web-Technologien wie HTML, CSS und JavaScript
- Grundkenntnisse in der Erstellung von Webanwendungen

Für Informationssystem und Embedded Systems ergeben sich andere Voraussetzungen.
Grundkenntnisse über die Architektur und Implementierung solcher Systeme reichen jedoch aus.

// end::DE[]

// tag::EN[]
=== Prerequisites

The requirements for training depend on the area on which the training focuses. For example, the requirements for security in the web area are:

-	Basic knowledge of network communication
-	Basic knowledge of web technologies such as HTML, CSS, and JavaScript
-	Basic knowledge of the creation of web applications

There are other requirements for information systems and embedded systems. However, basic knowledge of the architecture and implementation of such systems is sufficient.
// end::EN[]

