// tag::DE[]
=== Voraussetzungen

Die Voraussetzungen für das Training hängen von dem Bereich ab, auf den sich das Training fokussiert.

Beispielsweise sind die Voraussetzungen für Sicherheit im Web-Bereich:

-	Grundkenntnisse Netzwerkkommunikation
-	Grundkenntnisse in Web-Technologien wie

  * HTML
  * CSS
  * JavaScript
  
-	Grundkenntnisse in der Erstellung von Webanwendungen

Für Informationssystem und Embedded Systems ergeben sich andere Voraussetzungen.
Grundkenntnisse über die Architektur und Implementierung solcher Systeme reichen jedoch aus.

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Kenntnisgruppen sowie Voraussetzungen bitte entsprechend ausformulieren!
====
// end::REMARK[]
